export enum Permissions {
  MANAGE_UNIT_VIEW = "ManageUnit_View",
  MANAGE_UNIT_CREATE = "ManageUnit_Create",
  MANAGE_UNIT_UPDATE = "ManageUnit_Update",
  MANAGE_UNIT_DELETE = "ManageUnit_Delete",
  DEVICE_VIEW = "Device_View",
  DEVICE_CREATE = "Device_Create",
  DEVICE_UPDATE = "Device_Update",
  DEVICE_DELETE = "Device_Delete",
  DEVICE_EXPORT = "Device_Export",
  DEVICE_MANAGE = "Device_Manage",
  ACCOUNT_MANAGE = "Account_Manage",
  ACCOUNT_VIEW = "Account_View",
  ACCOUNT_CREATE = "Account_Create",
  ACCOUNT_UPDATE = "Account_Update",
  ACCOUNT_DELETE = "Account_Delete",
  EMPLOYEE_MANAGE = "Employee_Manage",
  EMPLOYEE_VIEW = "Employee_View",
  EMPLOYEE_CREATE = "Employee_Create",
  EMPLOYEE_UPDATE = "Employee_Update",
  EMPLOYEE_DELETE = "Employee_Delete",
  SEND_MESSAGE = "Send_Message",
}
