const API_URL = {
  GET_DEVICES: "/getDevices",
  GET_DEVICES_STATUS: "/getDeviceStatus",
  GET_INTERVALS: "/getIntervals",
  GET_DEVICES_SETUP_CHANNELS: "/getDeviceSetupChannels",
  CREATE_DEVICE: "/createDevice",
  DELETE_DEVICE: "/deleteDevice",
  UPDATE_DEVICE: "/updateDevice",
  GET_MANAGE_UNITS: "/getManageUnits",
  REQUEST: "/request",
  LOGIN: "/login",
  LOGOUT: "/logout",
  SIGNUP: "/signup",
  GET_USER: "/getUsers",
  GET_AUTH: "/getAuth",
  UPDATE_USER: "/updateUser",
  DELETE_USER: "/deleteUser",
  UPDATE_USER_PASSWORD: "/updateUserPassord",
  GET_EMPLOYEES: "/getEmployees",
  CREATE_EMPLOYEES: "/createEmployee",
  UPDATE_EMPLOYEES: "/updateEmployee",
  DELETE_EMPLOYEES: "/deleteEmployee",
  GET_NOTIFICATION_SETTINGS: "/getNotificationSetting",
  UPDATE_NOTIFICATION_SETTINGS: "/updateNotificationSetting",
}

export default API_URL
