name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Server
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_CONNECTION: ${{ secrets.SSH_CONNECTION }}
        run: |
          echo ${SSH_KEY}
          echo ${SSH_CONNECTION}
          # echo "$SSH_KEY"> key.pem
          # chmod 600 key.pem                
          # scp -i key.pem -r ./client/dist $USER@$HOST:/var/www/battery-mqtt/client/dist
          # scp -i key.pem -r ./server/dist $USER@$HOST:/var/www/battery-mqtt/server/dist
          # scp -i key.pem -r ./packages/drizzle/dist $USER@$HOST:/var/www/battery-mqtt/packages/drizzle/dist
          # scp -i key.pem -r ./packages/zod/dist $USER@$HOST:/var/www/battery-mqtt/packages/zod/dist
          # ssh -i key.pem $SSH_CONNECTION "cd /var/www/battery-mqtt && npm install && npm run build && pm2 restart battery"
